# Generated by Django 2.1.7 on 2019-03-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Malaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('malaria_img', models.ImageField(upload_to='images/')),
                ('prediction', models.CharField(max_length=50)),
            ],
        ),
    ]
