# Generated by Django 2.1.7 on 2019-03-08 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiseaseDetectionApp', '0002_userprofileinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancer_img', models.ImageField(upload_to='images/')),
                ('prediction', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='portfolio_site',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='profile_pic',
        ),
    ]
