# Generated by Django 2.1.7 on 2019-03-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiseaseDetectionApp', '0003_auto_20190308_0821'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiabeticRetinopathy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retina_img', models.ImageField(upload_to='images/')),
                ('prediction', models.CharField(max_length=50)),
            ],
        ),
    ]
